catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.7.3
  bumpp: ^10.3.2
  eslint: ^9.39.2
  tsdown: ^0.18.4
  typescript: ^5.9.3
  vite: ^7.3.0

catalogs:
  bench:
    '@types/commonmark': ^0.27.10
    '@types/markdown-it': ^14.1.2
    commonmark: ^0.31.2
    markdown-it: ^14.1.0
    marked: ^16.4.2
  docs:
    typedoc: ^0.28.15
    typedoc-plugin-frontmatter: ^1.3.1
    typedoc-plugin-markdown: ^4.9.0
    typedoc-vitepress-theme: ^1.1.2
    vitepress: 2.0.0-alpha.12
    vue: ^3.5.26
  integrations:
    entities: ^7.0.0
    linkify-it: ^5.0.0
    mdurl: ^2.0.0
    punycode.js: ^2.3.1
    uc.micro: ^2.1.0
  tests:
    js-yaml: ^4.1.1
    shiki: ^3.20.0
    tinyglobby: ^0.2.15
    vitest: ^4.0.16
  types:
    '@types/js-yaml': ^4.0.9
    '@types/linkify-it': ^5.0.0
    '@types/mdurl': ^2.0.0
    '@types/node': ^24.10.4

onlyBuiltDependencies:
  - esbuild
